### ISSUE TITLE
[BUG] /usr/share/ubios-udapi-server/ips/bin/getsig.sh Illegal number of parameters

### ISSUE THREAD

**Issue by bslatyer** [ymichel/dnsmasqAdBlockUDM#2]
Hey @ymichel,

I've encountered an error while using this script running on a UDM-SE v 3.2.7 (Early Access)

UniFi has changed how the IPS script is run on the Early Access Firmware.

Is this something that you can look into?

**Error**

```
Calling UDM script to reflect update immediately.
/usr/share/ubios-udapi-server/ips/bin/getsig.sh Illegal number of parameters
```
**Output of the script being run**
```
root@Redwood:/data/dns-filter# ./getBlacklistHosts.sh

.    Starting getBlacklistHosts V1.1 UDM...
.    Checking dependencies for getBlacklistHosts V1.1 UDM...
.    ....passed.
.    Target path for generated lists: /run/getBlacklistHosts
.    Adding the unifi-default blacklist...
.    Got 181366 records. Raw data count now: 181370
.    Not using a user-defined blacklist...
.    Not using any user-defined source URLs...
.    Using script-provided source URLs...
.    Downloading script-provided URL pi1 - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/multi.txt...
.    Got 761299 records. Raw data count now: 942670
.    Sanitizing downloaded blacklists...
.    Raw data stage 1 count: 942671
.    Raw data stage 2 count: 942652
.    Converting full blacklist...
.    Creating list of single domains...
.    Found 119793 single domains...
.    Removing sub-domains...
.    Not using a whitelist...
.    Old count: ...
.    New count (not using a whitelist): 270621...
.    Old count to new count change: +270621...
.    Purging temporary files...

.    Calling UDM script to repflect update immediately.
/usr/share/ubios-udapi-server/ips/bin/getsig.sh Illegal number of parameters
.    Script execution time: 25 seconds or 0 minutes 25 seconds
```

Thanks,

Braeden

**Comment by ymichel** [comment]
Hi Braedon,
since I am still on 8.0.7 (and do not have an eval-environment ready), I will either have to wait for the release candidate to be available or you sending me the getsig.sh script. 
Happy to further support!
BR,
Yann

**Comment by bslatyer** [comment]
Hey Yann,

No worries mate

Here's the script from the latest EA firmware

[getsig.sh.zip](https://github.com/ymichel/dnsmasqAdBlockUDM/files/13628964/getsig.sh.zip)

Feel free to let me know if you need anything else.

Thanks,

Braeden

**Comment by ymichel** [comment]
Hi Braedon,
a first look into the file clarified that Unify did change a couple of things so I will have to reword the script, i.e., adjust it accordingly (and will since I am using it myself).
…but since it is already a release-candidate, it will most likely be public ally stable anytime soon.
BR,
Yann

**Comment by ymichel** [comment]
…and already have some idea on how to do that already but will check myself first ;-)

**Comment by bslatyer** [comment]
Hey Yann,

Awesome!

Looking forward to seeing what the changes bring :)

Thanks,

Braeden

**Comment by ymichel** [comment]
Should be solved now with Release V1.2 :-)

**Comment by ymichel** [comment]
Feedback welcome ;-)

**Comment by bslatyer** [comment]
Hey @ymichel,

LGTM!

Thanks again :)

**Comment by ymichel** [comment]
V1.3-UDM now also provides a hint in the email in case enabled in case there is a new update available.
